-- MySQL Script generated by MySQL Workbench
-- mar 14 jul 2015 21:48:14 COT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ingenia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ingenia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ingenia` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ingenia` ;

-- -----------------------------------------------------
-- Table `ingenia`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`usuario` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellido` VARCHAR(45) NULL COMMENT '',
  `genero` VARCHAR(45) NULL COMMENT '',
  `correo` VARCHAR(45) NULL COMMENT '',
  `fecha_creacion` DATETIME NULL DEFAULT now() COMMENT '',
  `fecha_ultimo_ingreso` DATETIME NOT NULL DEFAULT now() COMMENT '',
  `clave` VARCHAR(45) NULL COMMENT '',
  `alias` VARCHAR(45) NULL COMMENT '',
  `identificacion` INT NULL COMMENT '',
  PRIMARY KEY (`idusuario`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `ingenia`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`curso` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(65) NOT NULL COMMENT '',
  `descripcion` VARCHAR(300) NULL COMMENT '',
  `activo` INT NULL COMMENT '',
  `estado` VARCHAR(11) NULL COMMENT '',
  `idprofesor` INT NOT NULL COMMENT '',
  `limite_actividades` INT NULL COMMENT '',
  PRIMARY KEY (`idcurso`)  COMMENT '',
  INDEX `fk_curso_usuario1_idx` (`idprofesor` ASC)  COMMENT '',
  CONSTRAINT `fk_curso_usuario1`
    FOREIGN KEY (`idprofesor`)
    REFERENCES `ingenia`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`estudiantecurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`estudiantecurso` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`estudiantecurso` (
  `idcurso` INT NOT NULL COMMENT '',
  `idusuario` INT NOT NULL COMMENT '',
  `puntaje` INT NULL COMMENT 'puntaje obtenido por un jugador en un curso.',
  PRIMARY KEY (`idcurso`, `idusuario`)  COMMENT '',
  INDEX `fk_curso_estudiante_usuario1_idx` (`idusuario` ASC)  COMMENT '',
  CONSTRAINT `fk_curso_estudiante_curso`
    FOREIGN KEY (`idcurso`)
    REFERENCES `ingenia`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_estudiante_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `ingenia`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`juego`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`juego` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`juego` (
  `idjuego` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(65) NULL COMMENT '',
  `descripcion_juego` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idjuego`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`actividad` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`actividad` (
  `idactividad` INT NOT NULL COMMENT '',
  `idtipo_juego` INT NOT NULL COMMENT '',
  `activo` INT NULL COMMENT 'estado activo o inactivo',
  `publicado` INT NULL COMMENT '',
  `limite_movimientos` INT NOT NULL COMMENT '',
  `enunciado` VARCHAR(45) NULL COMMENT '',
  `url_texto_ensenanza` VARCHAR(255) NULL COMMENT '',
  `idprofesor` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idactividad`)  COMMENT '',
  INDEX `fk_actividad_tipo_actividad1_idx` (`idtipo_juego` ASC)  COMMENT '',
  INDEX `fk_actividad_usuario1_idx` (`idprofesor` ASC)  COMMENT '',
  CONSTRAINT `fk_actividad_tipo_actividad1`
    FOREIGN KEY (`idtipo_juego`)
    REFERENCES `ingenia`.`juego` (`idjuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_usuario1`
    FOREIGN KEY (`idprofesor`)
    REFERENCES `ingenia`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`actividadcurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`actividadcurso` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`actividadcurso` (
  `idcurso` INT NOT NULL COMMENT '',
  `posicion_actividad` INT NOT NULL COMMENT 'posicion dentro de la secuencia de actividades que deben aparecer en un curso.\n',
  `idactividad` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idcurso`, `idactividad`)  COMMENT '',
  INDEX `fk_curso_actividad_actividad1_idx` (`idactividad` ASC)  COMMENT '',
  CONSTRAINT `fk_curso_actividad_curso1`
    FOREIGN KEY (`idcurso`)
    REFERENCES `ingenia`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_actividad_actividad1`
    FOREIGN KEY (`idactividad`)
    REFERENCES `ingenia`.`actividad` (`idactividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`mensaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`mensaje` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`mensaje` (
  `idmensaje` INT NOT NULL COMMENT '',
  `idusuario_origen` INT NOT NULL COMMENT '',
  `idusuario_destino` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idmensaje`)  COMMENT '',
  INDEX `fk_mensaje_usuario1_idx` (`idusuario_origen` ASC)  COMMENT '',
  INDEX `fk_mensaje_usuario2_idx` (`idusuario_destino` ASC)  COMMENT '',
  CONSTRAINT `fk_mensaje_usuario1`
    FOREIGN KEY (`idusuario_origen`)
    REFERENCES `ingenia`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensaje_usuario2`
    FOREIGN KEY (`idusuario_destino`)
    REFERENCES `ingenia`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`respuesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`respuesta` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`respuesta` (
  `idrespuesta` INT NOT NULL COMMENT '',
  `idactividad` INT NOT NULL COMMENT '',
  `valor` VARCHAR(45) NULL COMMENT 'opcion de respuesta, algunas no seran verdaderas. Corresponde a las opciones que el usuario tiene para seleccionar la respuesta correcta.',
  `verdadero` TINYINT(1) NULL COMMENT 'identifica si esta es la respuesta correcta',
  `orden` INT NULL COMMENT '',
  PRIMARY KEY (`idrespuesta`)  COMMENT '',
  INDEX `fk_respuestas_actividad1_idx` (`idactividad` ASC)  COMMENT '',
  CONSTRAINT `fk_respuestas_actividad1`
    FOREIGN KEY (`idactividad`)
    REFERENCES `ingenia`.`actividad` (`idactividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`tipogato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`tipogato` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`tipogato` (
  `idtipogato` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtipogato`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`color` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`color` (
  `idcolor` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idcolor`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`arma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`arma` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`arma` (
  `idarma` INT NOT NULL COMMENT '',
  `nombre_arma` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idarma`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`gato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`gato` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`gato` (
  `idgato` INT NOT NULL COMMENT '',
  `idtipo_gato` INT NOT NULL COMMENT '',
  `orden` INT NOT NULL COMMENT '',
  `defensa` INT NOT NULL COMMENT '',
  `idcolor` INT NOT NULL COMMENT '',
  `idarma` INT NOT NULL COMMENT '',
  `idactividad` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idgato`)  COMMENT '',
  INDEX `fk_gato_tipo_gato1_idx` (`idtipo_gato` ASC)  COMMENT '',
  INDEX `fk_gato_color1_idx` (`idcolor` ASC)  COMMENT '',
  INDEX `fk_gato_arma1_idx` (`idarma` ASC)  COMMENT '',
  INDEX `fk_gato_actividad1_idx` (`idactividad` ASC)  COMMENT '',
  CONSTRAINT `fk_gato_tipo_gato1`
    FOREIGN KEY (`idtipo_gato`)
    REFERENCES `ingenia`.`tipogato` (`idtipogato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gato_color1`
    FOREIGN KEY (`idcolor`)
    REFERENCES `ingenia`.`color` (`idcolor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gato_arma1`
    FOREIGN KEY (`idarma`)
    REFERENCES `ingenia`.`arma` (`idarma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gato_actividad1`
    FOREIGN KEY (`idactividad`)
    REFERENCES `ingenia`.`actividad` (`idactividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`estructura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`estructura` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`estructura` (
  `idestructura` INT NOT NULL COMMENT '',
  `nombre_estrucutra` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idestructura`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`estructurabloqueada_actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`estructurabloqueada_actividad` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`estructurabloqueada_actividad` (
  `idestructura` INT NOT NULL COMMENT '',
  `idactividad` INT NOT NULL COMMENT '',
  INDEX `fk_actividadjuego_estructura_estructura1_idx` (`idestructura` ASC)  COMMENT '',
  PRIMARY KEY (`idactividad`, `idestructura`)  COMMENT '',
  CONSTRAINT `fk_actividadjuego_estructura_estructura1`
    FOREIGN KEY (`idestructura`)
    REFERENCES `ingenia`.`estructura` (`idestructura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_estructura_actividad1`
    FOREIGN KEY (`idactividad`)
    REFERENCES `ingenia`.`actividad` (`idactividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`movimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`movimiento` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`movimiento` (
  `idmovimientos` INT NOT NULL COMMENT '',
  `nombre_movimiento` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idmovimientos`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`raton`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`raton` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`raton` (
  `idraton` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idraton`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`actividadusuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`actividadusuario` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`actividadusuario` (
  `usuario_idusuario` INT NOT NULL COMMENT '',
  `actividad_idactividad` INT NOT NULL COMMENT '',
  `raton_idraton` INT NOT NULL COMMENT '',
  `numero_intento` INT NULL COMMENT '',
  `Fecha` DATE NOT NULL COMMENT '',
  `Puntos` INT NULL COMMENT '',
  PRIMARY KEY (`usuario_idusuario`, `actividad_idactividad`, `raton_idraton`)  COMMENT '',
  INDEX `fk_usuario_actividad_usuario1_idx` (`usuario_idusuario` ASC)  COMMENT '',
  INDEX `fk_usuario_actividad_actividad1_idx` (`actividad_idactividad` ASC)  COMMENT '',
  INDEX `fk_usuario_actividad_raton1_idx` (`raton_idraton` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_actividad_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `ingenia`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_actividad_actividad1`
    FOREIGN KEY (`actividad_idactividad`)
    REFERENCES `ingenia`.`actividad` (`idactividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_actividad_raton1`
    FOREIGN KEY (`raton_idraton`)
    REFERENCES `ingenia`.`raton` (`idraton`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`estructuraraton`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`estructuraraton` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`estructuraraton` (
  `idestructura` INT NOT NULL COMMENT '',
  `idraton` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idestructura`, `idraton`)  COMMENT '',
  INDEX `fk_estructura_raton_raton1_idx` (`idraton` ASC)  COMMENT '',
  CONSTRAINT `fk_estructura_raton_estructura1`
    FOREIGN KEY (`idestructura`)
    REFERENCES `ingenia`.`estructura` (`idestructura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estructura_raton_raton1`
    FOREIGN KEY (`idraton`)
    REFERENCES `ingenia`.`raton` (`idraton`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`movimientoraton`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`movimientoraton` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`movimientoraton` (
  `idraton` INT NOT NULL COMMENT '',
  `idmovimiento` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idraton`, `idmovimiento`)  COMMENT '',
  INDEX `fk_movimientos_raton_movimientos1_idx` (`idmovimiento` ASC)  COMMENT '',
  CONSTRAINT `fk_movimientos_raton_raton1`
    FOREIGN KEY (`idraton`)
    REFERENCES `ingenia`.`raton` (`idraton`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimientos_raton_movimientos1`
    FOREIGN KEY (`idmovimiento`)
    REFERENCES `ingenia`.`movimiento` (`idmovimientos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`rol` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`rol` (
  `idRol` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `estado` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idRol`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`rolusuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`rolusuario` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`rolusuario` (
  `idRol` INT NOT NULL COMMENT '',
  `idusuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idRol`, `idusuario`)  COMMENT '',
  INDEX `fk_rolXusuario_usuario1_idx` (`idusuario` ASC)  COMMENT '',
  CONSTRAINT `fk_rolXusuario_rol1`
    FOREIGN KEY (`idRol`)
    REFERENCES `ingenia`.`rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rolXusuario_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `ingenia`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`opcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`opcion` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`opcion` (
  `idopcion` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `descripcion` VARCHAR(300) NULL COMMENT '',
  `codigo` VARCHAR(5) NULL COMMENT '',
  PRIMARY KEY (`idopcion`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ingenia`.`opcionrol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ingenia`.`opcionrol` ;

CREATE TABLE IF NOT EXISTS `ingenia`.`opcionrol` (
  `idopcion` INT NOT NULL COMMENT '',
  `idRol` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idopcion`, `idRol`)  COMMENT '',
  INDEX `fk_opcionXrol_rol1_idx` (`idRol` ASC)  COMMENT '',
  CONSTRAINT `fk_opcionXrol_opcion1`
    FOREIGN KEY (`idopcion`)
    REFERENCES `ingenia`.`opcion` (`idopcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_opcionXrol_rol1`
    FOREIGN KEY (`idRol`)
    REFERENCES `ingenia`.`rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
